name: build-thedora
on:
  #  pull_request:
  #    branches:
  #      - main
  #  schedule:
  #    - cron: '20 20 * * *'  # 8:20pm everyday
    push:
      branches:
        - main
jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    container:
      image: registry.fedoraproject.org/fedora:37
      options: --privileged
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Install build dependencies
        run: dnf install -y ostree rpm-ostree tar git rpm-ostree selinux-policy selinux-policy-targeted policycoreutils binutils

      - name: Checkout This Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Move files from workstation-ostree-config to this dir
        run: mv workstation-ostree-config/* .

      - name: Get Date for Cache
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%V")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Init build
        run: |
          mkdir -p repo cache
          ostree --repo=repo init --mode=archive

      - name: Cache
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build tree
        run: sudo rpm-ostree compose tree --repo=repo --unified-core --cachedir=cache thedora.yaml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docker image
        run: sudo rpm-ostree compose container-encapsulate --repo=repo fedora/37/x86_64/thedora docker://ghcr.io/thobianchi/thedora:37

      ## Push the image to GHCR (Image Registry)
      #- name: Push To GHCR
      #  uses: redhat-actions/push-to-registry@v2
      #  id: push
      #  env:
      #    REGISTRY_USER: ${{ github.actor }}
      #  with:
      #    image: ${{ steps.build_image.outputs.image }}
      #    tags: ${{ steps.build_image.outputs.tags }}
      #    registry: ${{ steps.registry_case.outputs.lowercase }}
      #    username: ${{ env.REGISTRY_USER }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      #    extra-args: |
      #      --disable-content-trust

