name: build-thedora
on:
  #  pull_request:
  #    branches:
  #      - main
  #  schedule:
  #    - cron: '20 20 * * *'  # 8:20pm everyday
    push:
      branches:
        - main
jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    container:
      image: registry.fedoraproject.org/fedora:37
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Install build dependencies
        run: dnf install -y ostree rpm-ostree tar git rpm-ostree selinux-policy selinux-policy-targeted policycoreutils binutils rsync

          #- name: Install Docker CLI
          #  run: |
          #    export DOCKERVERSION=18.03.1-ce
          #    curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz   && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1                  -C /usr/local/bin docker/docker   && rm -f docker-${DOCKERVERSION}.tgz

      - name: Checkout This Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Move files from workstation-ostree-config to this dir
        run: mv workstation-ostree-config/* .

      - name: Get Date for Cache
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%V")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Init build
        run: |
          mkdir -p repo cache
          ostree --repo=repo init --mode=archive

      - name: Cache
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build tree
        run: |
          sudo rpm-ostree compose tree --repo=repo --unified-core --cachedir=cache thedora.yaml
          ostree summary --repo=repo --update

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: repo

      #- name: Login to GitHub Container Registry
      #  run: |
      #    skopeo login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      #- name: Create docker image
      #  run: sudo rpm-ostree compose container-encapsulate --repo=repo fedora/37/x86_64/thedora docker://ghcr.io/thobianchi/thedora:37

      ## Push the image to GHCR (Image Registry)
      #- name: Push To GHCR
      #  uses: redhat-actions/push-to-registry@v2
      #  id: push
      #  env:
      #    REGISTRY_USER: ${{ github.actor }}
      #  with:
      #    image: ${{ steps.build_image.outputs.image }}
      #    tags: ${{ steps.build_image.outputs.tags }}
      #    registry: ${{ steps.registry_case.outputs.lowercase }}
      #    username: ${{ env.REGISTRY_USER }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      #    extra-args: |
      #      --disable-content-trust

