name: build-thedora
on:
  #  pull_request:
  #    branches:
  #      - main
  #  schedule:
  #    - cron: '20 20 * * *'  # 8:20pm everyday
    push:
      branches:
        - main
jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    container: 
      image: registry.fedoraproject.org/fedora-minimal:37
    permissions:
      contents: read
      packages: write
      id-token: write

    steps: 
      - name: Install ostree
        run: microdnf install -y ostree rpm-ostree tar git

      - name: Checkout This Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Move files from workstation-ostree-config to this dir
        run: mv workstation-ostree-config/* .

      # Cache
      
      - name: Init build
        run: |
          mkdir -p repo cache
          ostree --repo=repo init --mode=archive

      - name: Build tree
        run: rpm-ostree compose tree --repo=repo --unified-core --cachedir=cache thedora.yaml

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      ## Push the image to GHCR (Image Registry)
      #- name: Push To GHCR
      #  uses: redhat-actions/push-to-registry@v2
      #  id: push
      #  env:
      #    REGISTRY_USER: ${{ github.actor }}
      #  with:
      #    image: ${{ steps.build_image.outputs.image }}
      #    tags: ${{ steps.build_image.outputs.tags }}
      #    registry: ${{ steps.registry_case.outputs.lowercase }}
      #    username: ${{ env.REGISTRY_USER }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      #    extra-args: |
      #      --disable-content-trust

